name: Manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: choice
                options: 
                    - hi
                    - hello
                    - test
                default: Hello
                required: true
                description: A cheerful word
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run:
                echo "${{inputs.greeting}}"
                echo "${{github.actor}}"
                echo "${{github.workspace}}"
